/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "outline-variant": "#c7c4d7",
        "on-surface-variant": "#464554",
        "secondary-fixed-dim": "#4edea3",
        "surface-card": "#FFFFFF",
        "on-tertiary-fixed-variant": "#653e00",
        "error": "#ba1a1a",
        "on-primary-fixed": "#07006c",
        "primary-container": "#6063ee",
        "inverse-surface": "#303030",
        "surface-variant": "#e5e2e1",
        "error-red": "#F44336",
        "on-secondary-fixed": "#002113",
        "on-error-container": "#93000a",
        "surface-container-high": "#eae7e7",
        "on-background": "#1b1c1c",
        "background": "#fcf9f8",
        "on-tertiary-fixed": "#2a1700",
        "vibrant-indigo": "#6366F1",
        "sunny-amber": "#F59E0B",
        "on-secondary-fixed-variant": "#005236",
        "outline": "#767586",
        "surface-dim": "#dcd9d9",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#a36700",
        "fresh-mint": "#10B981",
        "surface-bg": "#F5F5F5",
        "surface-tint": "#494bd6",
        "primary-fixed": "#e1e0ff",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#ffb95f",
        "inverse-on-surface": "#f3f0ef",
        "border-subtle": "#E0E0E0",
        "on-tertiary-container": "#fffbff",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container-low": "#f6f3f2",
        "on-error": "#ffffff",
        "secondary-fixed": "#6ffbbe",
        "on-surface": "#1b1c1c",
        "secondary-container": "#6cf8bb",
        "tertiary-fixed": "#ffddb8",
        "surface-container-highest": "#e5e2e1",
        "surface-container": "#f0eded",
        "on-primary-container": "#fffbff",
        "on-secondary-container": "#00714d",
        "tertiary": "#825100",
        "primary": "#4648d4",
        "secondary": "#006c49",
        "surface": "#fcf9f8",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fcf9f8",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-primary": "#c0c1ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "sm": "8px",
        "base": "4px",
        "margin-mobile": "16px",
        "gutter": "16px",
        "xl": "40px",
        "xs": "4px",
        "md": "16px",
        "lg": "24px"
      },
      fontFamily: {
        "display-lg": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"]
      },
      boxShadow: {
        'level-1': '0px 4px 12px rgba(0, 0, 0, 0.08)',
        'level-2': '0px 8px 24px rgba(0, 0, 0, 0.12)',
        'level-3': '0px 12px 32px rgba(0, 0, 0, 0.15)',
      }
    },
  },
  plugins: [],
}
